using System.Collections.Generic;
using System.IO;

namespace MacFree.Editor
{
    /// Writes the post-build upload hook into the user's repository. Two
    /// copies: repo root and Unity project root - Unity Build Automation
    /// resolves the script path relative to the project SUBFOLDER, so the
    /// project copy is the one it finds when the game lives in a subdir.
    public static class ProjectPatcher
    {
        public static string UploadScriptContent()
        {
            return string.Join("\n", new[]
            {
"#!/usr/bin/env bash",
"# MacFree - iOS Builder: post-build TestFlight upload (runs on the Unity",
"# Build Automation Mac). Generated by MacFree; safe to commit.",
"set -uo pipefail",
"",
"echo \"=== MacFree upload ===\"",
"",
"for v in MACFREE_ASC_KEY_ID MACFREE_ASC_ISSUER_ID MACFREE_ASC_KEY_B64; do",
"  if [ -z \"${!v:-}\" ]; then",
"    echo \"ERROR: env var $v is not set on the build target.\"",
"    exit 1",
"  fi",
"done",
"",
"# Locate the .ipa: UNITY_PLAYER_PATH on success, newest .ipa as fallback.",
"IPA=\"\"",
"if [ -n \"${UNITY_PLAYER_PATH:-}\" ] && [ -f \"$UNITY_PLAYER_PATH\" ] && [[ \"$UNITY_PLAYER_PATH\" == *.ipa ]]; then",
"  IPA=\"$UNITY_PLAYER_PATH\"",
"elif [ -n \"${UNITY_PLAYER_PATH:-}\" ] && [ -d \"$UNITY_PLAYER_PATH\" ]; then",
"  IPA=\"$(find \"$UNITY_PLAYER_PATH\" -name '*.ipa' -print 2>/dev/null | head -n1)\"",
"fi",
"if [ -z \"$IPA\" ]; then",
"  for root in \"${WORKSPACE:-}\" \"${BUILD_PATH:-}\" \"$(pwd)\" \"$HOME\"; do",
"    [ -n \"$root\" ] && [ -d \"$root\" ] || continue",
"    IPA=\"$(find \"$root\" -name '*.ipa' -type f 2>/dev/null | head -n1)\"",
"    [ -n \"$IPA\" ] && break",
"  done",
"fi",
"if [ -z \"$IPA\" ] || [ ! -f \"$IPA\" ]; then",
"  echo \"No .ipa found (build likely failed) - skipping upload.\"",
"  exit 0",
"fi",
"echo \"IPA: $IPA\"",
"",
"KEY_DIR=\"$HOME/.appstoreconnect/private_keys\"",
"mkdir -p \"$KEY_DIR\"",
"KEY_FILE=\"$KEY_DIR/AuthKey_${MACFREE_ASC_KEY_ID}.p8\"",
"echo \"$MACFREE_ASC_KEY_B64\" | base64 --decode > \"$KEY_FILE\"",
"chmod 600 \"$KEY_FILE\"",
"trap 'rm -f \"$KEY_FILE\"' EXIT",
"",
"xcrun altool --upload-app -f \"$IPA\" -t ios \\",
"  --apiKey \"$MACFREE_ASC_KEY_ID\" --apiIssuer \"$MACFREE_ASC_ISSUER_ID\"",
"rc=$?",
"if [ $rc -ne 0 ]; then",
"  echo \"ERROR: altool upload failed (exit $rc) - see lines above for Apple's reason.\"",
"  exit $rc",
"fi",
"",
"echo \"MacFree: upload complete - TestFlight shows it after Apple processing.\"",
""
            });
        }

        public static string[] WriteHooks(string unityProjectRoot)
        {
            string repoRoot = FindRepoRoot(unityProjectRoot) ?? unityProjectRoot;
            var written = new List<string>();
            foreach (string root in new[] { repoRoot, unityProjectRoot })
            {
                string path = Path.Combine(root, "ci", "macfree-upload.sh");
                if (written.Contains(path)) continue;
                Directory.CreateDirectory(Path.GetDirectoryName(path));
                // LF endings: the script runs on macOS.
                File.WriteAllText(path, UploadScriptContent());
                written.Add(path);
            }
            return written.ToArray();
        }

        internal static string FindRepoRoot(string start)
        {
            var dir = new DirectoryInfo(start);
            while (dir != null)
            {
                if (Directory.Exists(Path.Combine(dir.FullName, ".git"))) return dir.FullName;
                dir = dir.Parent;
            }
            return null;
        }

        /// Stage and commit the hook files automatically, so the user never
        /// has to click "Commit files". Best-effort and silent: no-ops if git
        /// is missing, this isn't an initialized repo, or nothing changed.
        public static void CommitHooks(string unityProjectRoot)
        {
            string repoRoot = FindRepoRoot(unityProjectRoot);
            if (repoRoot == null) return;
            // Only touch a real, initialized repo (a plain .git dir with no HEAD
            // is not one — this also keeps unit tests from spawning git).
            if (!File.Exists(Path.Combine(repoRoot, ".git", "HEAD"))) return;
            RunGit(repoRoot, "add ci Assets/MacFree");
            RunGit(repoRoot, "commit -m \"MacFree: add build hooks\"");
        }

        static void RunGit(string repoRoot, string args)
        {
            RunGit(repoRoot, args, 15000);
        }

        /// Runs git and RETURNS (exitCode, stdout+stderr) so callers that must
        /// know whether a push actually succeeded can react. Throws nothing.
        static (int code, string output) RunGitChecked(string repoRoot, string args, int timeoutMs)
        {
            try
            {
                var psi = new System.Diagnostics.ProcessStartInfo("git", args)
                {
                    WorkingDirectory = repoRoot,
                    UseShellExecute = false,
                    CreateNoWindow = true,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true
                };
                // Never let git block on an interactive credential/terminal
                // prompt (headless): fail fast instead of hanging.
                psi.EnvironmentVariables["GIT_TERMINAL_PROMPT"] = "0";
                psi.EnvironmentVariables["GCM_INTERACTIVE"] = "never";
                using (var p = System.Diagnostics.Process.Start(psi))
                {
                    // Drain BOTH pipes concurrently. git push writes its
                    // progress to stderr; reading stdout to completion first
                    // (as before) deadlocks once stderr's buffer fills.
                    var so = p.StandardOutput.ReadToEndAsync();
                    var se = p.StandardError.ReadToEndAsync();
                    if (!p.WaitForExit(timeoutMs))
                    {
                        try { p.Kill(); } catch { }
                        return (-1, "git timed out after " + (timeoutMs / 1000) + "s");
                    }
                    p.WaitForExit(); // let the async reads flush after exit
                    string output = ((so.Result ?? "") + "\n" + (se.Result ?? "")).Trim();
                    return (p.ExitCode, output);
                }
            }
            catch (System.Exception e) { return (-1, e.Message); }
        }

        static void RunGit(string repoRoot, string args, int timeoutMs)
        {
            RunGitChecked(repoRoot, args, timeoutMs);
        }

        /// A minimal, safe Unity .gitignore so init doesn't commit Library/,
        /// Temp/, or UserSettings/ (which holds MacFree's signing secrets).
        const string UnityGitignore =
            "[Ll]ibrary/\n[Tt]emp/\n[Oo]bj/\n[Bb]uild/\n[Bb]uilds/\n[Ll]ogs/\n" +
            "[Uu]serSettings/\n[Mm]emoryCaptures/\n.vs/\n.gradle/\n" +
            "*.csproj\n*.sln\n*.unityproj\n*.suo\n*.user\n*.tmp\n.DS_Store\n";

        /// Turn the project into a Git repo (if it isn't one), commit
        /// everything, point 'origin' at cloneUrl, and push 'main'. The token
        /// is injected into the push URL only (never written to git config, so
        /// it can't leak into the repo). Returns true only if the push
        /// succeeds — Build Automation can't build until the code is on the
        /// remote. Throws with the git output on failure so the UI can show it.
        public static void InitCommitAndPush(string unityProjectRoot,
            string cloneUrl, string token)
        {
            string root = FindRepoRoot(unityProjectRoot) ?? unityProjectRoot;
            if (!Directory.Exists(Path.Combine(root, ".git")))
            {
                RunGit(root, "init");
                RunGit(root, "symbolic-ref HEAD refs/heads/main");
            }
            // Clear a stale index lock left by an interrupted/killed git so
            // add/commit aren't silently blocked (which leaves no commit).
            SafeDelete(Path.Combine(root, ".git", "index.lock"));
            // Guarantee Library/, Temp/, UserSettings/, etc. are ignored even
            // when a minimal .gitignore already exists (Unity's default, or the
            // UserSettings-only one MacFree's preflight fix writes). Without
            // this, 'git add -A' stages hundreds of MB of Library/.
            EnsureUnityGitignore(root);

            // Identity so commit never fails on a machine without global config.
            RunGit(root, "config user.email macfree@localhost");
            RunGit(root, "config user.name MacFree");
            // Reset staging so anything staged before the ignore was fixed
            // (e.g. Library/) is dropped, then stage what the ignore now allows.
            RunGit(root, "rm -r --cached --ignore-unmatch -q .");
            RunGit(root, "add -A");
            RunGit(root, "commit -m \"MacFree: project + iOS build hook\"");

            // Fail clearly if no commit was produced, rather than pushing an
            // unborn HEAD (git's opaque "src refspec HEAD does not match any").
            var (headCode, _) = RunGitChecked(root, "rev-parse --verify HEAD", 15000);
            if (headCode != 0)
                throw new MacFreeApiException("Commit", -1,
                    "No commit was created, so there is nothing to push. Make sure "
                    + "the project has committable files and that git works from a terminal.");

            // Push over an authenticated URL built on the fly; never persisted.
            string authUrl = InjectToken(cloneUrl, token);
            var (code, output) = RunGitChecked(root,
                "-c credential.helper= -c http.sslBackend=schannel "
                + "-c http.schannelCheckRevoke=false push " + authUrl + " HEAD:main", 180000);
            if (code != 0)
                throw new MacFreeApiException("Push to GitHub", code,
                    Sanitize(output, token));
        }

        static void SafeDelete(string path)
        {
            try { if (File.Exists(path)) File.Delete(path); } catch { }
        }

        /// Append the Unity ignore block unless the .gitignore already carries
        /// it (detected by the Library pattern), so an existing minimal file
        /// isn't clobbered but Library/Temp/UserSettings are always excluded.
        static void EnsureUnityGitignore(string root)
        {
            string gi = Path.Combine(root, ".gitignore");
            string existing = File.Exists(gi) ? File.ReadAllText(gi) : "";
            if (existing.IndexOf("[Ll]ibrary/", System.StringComparison.Ordinal) >= 0) return;
            if (existing.Length > 0 && !existing.EndsWith("\n")) existing += "\n";
            File.WriteAllText(gi, existing + UnityGitignore);
        }

        static string InjectToken(string cloneUrl, string token)
        {
            const string https = "https://";
            if (cloneUrl.StartsWith(https) && !string.IsNullOrEmpty(token))
                return https + "x-access-token:" + token + "@" + cloneUrl.Substring(https.Length);
            return cloneUrl;
        }

        static string Sanitize(string s, string token)
        {
            return string.IsNullOrEmpty(token) ? s : s.Replace(token, "***");
        }
    }
}
