#!/usr/bin/env bash
# MacFree - iOS Builder: post-build TestFlight upload (runs on the Unity
# Build Automation Mac). Generated by MacFree; safe to commit.
set -uo pipefail

echo "=== MacFree upload ==="

for v in MACFREE_ASC_KEY_ID MACFREE_ASC_ISSUER_ID MACFREE_ASC_KEY_B64; do
  if [ -z "${!v:-}" ]; then
    echo "ERROR: env var $v is not set on the build target."
    exit 1
  fi
done

# Locate the .ipa: UNITY_PLAYER_PATH on success, newest .ipa as fallback.
IPA=""
if [ -n "${UNITY_PLAYER_PATH:-}" ] && [ -f "$UNITY_PLAYER_PATH" ] && [[ "$UNITY_PLAYER_PATH" == *.ipa ]]; then
  IPA="$UNITY_PLAYER_PATH"
elif [ -n "${UNITY_PLAYER_PATH:-}" ] && [ -d "$UNITY_PLAYER_PATH" ]; then
  IPA="$(find "$UNITY_PLAYER_PATH" -name '*.ipa' -print 2>/dev/null | head -n1)"
fi
if [ -z "$IPA" ]; then
  for root in "${WORKSPACE:-}" "${BUILD_PATH:-}" "$(pwd)" "$HOME"; do
    [ -n "$root" ] && [ -d "$root" ] || continue
    IPA="$(find "$root" -name '*.ipa' -type f 2>/dev/null | head -n1)"
    [ -n "$IPA" ] && break
  done
fi
if [ -z "$IPA" ] || [ ! -f "$IPA" ]; then
  echo "No .ipa found (build likely failed) - skipping upload."
  exit 0
fi
echo "IPA: $IPA"

KEY_DIR="$HOME/.appstoreconnect/private_keys"
mkdir -p "$KEY_DIR"
KEY_FILE="$KEY_DIR/AuthKey_${MACFREE_ASC_KEY_ID}.p8"
echo "$MACFREE_ASC_KEY_B64" | base64 --decode > "$KEY_FILE"
chmod 600 "$KEY_FILE"
trap 'rm -f "$KEY_FILE"' EXIT

xcrun altool --upload-app -f "$IPA" -t ios \
  --apiKey "$MACFREE_ASC_KEY_ID" --apiIssuer "$MACFREE_ASC_ISSUER_ID"
rc=$?
if [ $rc -ne 0 ]; then
  echo "ERROR: altool upload failed (exit $rc) - see lines above for Apple's reason."
  exit $rc
fi

echo "MacFree: upload complete - TestFlight shows it after Apple processing."
